// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kltlarwazpdktuwhlwwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsdGxhcndhenBka3R1d2hsd3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTYxMzAsImV4cCI6MjA2MzgzMjEzMH0.oSb7AUWurndIdx99Y1l6OR7qvjF8wUy1_bGfq5MV_k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);